apiVersion: infrastructure.cci.vmware.com/v1alpha1
kind: SupervisorNamespaceClassConfig
metadata:
  name: hol-ns-class   # your class name here
spec:
  storageClasses:
    - name: tanzu-storage-policy  # your storage class name that maps to your vCenter policy here
  vmClasses:
    - name: best-effort-small
    - name: best-effort-xsmall
    - name: best-effort-medium
  contentSources:
    - name: "holcontentlibrary"  # this is your VM content source.  Not your TKR content source
      type: ContentLibrary
  # Below limits are an EXAMPLE! Setting them may cause unexpected behavior in your namespace
  # Either set reasonable limits, or remove the below section to get unlimited resources
  limits:
    - name: pod_count
      limit: "((parameters.podCountLimit))"
  supervisorSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - development   # your tag name here