apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cci-service.fling.vsphere.vmware.com.0.0.1
spec:
  refName: cci-service.fling.vsphere.vmware.com
  version: 0.0.1
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.packages.broadcom.com/vcf_cci_service/cci-supervisor-service-package:v0.0.1
      template:
      - ytt:
          paths:
          - config/
          ignoreUnknownComments: true
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: cci-service.fling.vsphere.vmware.com
spec:
  displayName: CCI Service
  shortDescription: Provides integration between supervisor and Aria Automation Cloud Consumption Interface.
  longDescription: Provides integration between supervisor and Aria Automation Cloud Consumption Interface.
  providerName: VMware
